<template>
  <TwoColumnBlockItem
    :description="$t('Add an extra layer of security to your account using two-factor authentication.')"
    :title="$t('Two-factor authentication')"
    data-cy="2fa-form"
  >
    <div
      class="max-w-md space-y-10 rounded-md border border-zinc-900/20 bg-white p-3 shadow-sm dark:border-white/20 dark:bg-zinc-950"
    >
      <div v-if="!showSetup" class="flex items-center justify-between">
        <div class="flex items-center gap-4">
          <LockClosedIcon v-if="user.two_factor_enabled" class="h-5 w-5 text-emerald-600 dark:text-emerald-500" />
          <LockOpenIcon v-else class="h-5 w-5 text-rose-600 dark:text-rose-500" />
          <BaseBadge :variant="user.two_factor_enabled ? 'success' : 'danger'">
            {{ user.two_factor_enabled ? $t('Enabled') : $t('Disabled') }}
          </BaseBadge>
        </div>

        <BaseButton
          v-if="user.two_factor_enabled"
          :loading="loading"
          data-cy="disable-2fa-button"
          variant="secondary"
          @click="disableTwoFactor"
        >
          {{ $t('Disable 2FA') }}
        </BaseButton>

        <BaseButton v-else :loading="loading" data-cy="enable-2fa-button" @click="enableTwoFactor">
          {{ $t('Enable 2FA') }}
        </BaseButton>
      </div>

      <template v-else>
        <article>
          <h3 class="text-sm font-medium text-zinc-900 dark:text-white">
            {{ $t('Finish setup') }}
          </h3>
          <p class="mt-1 text-sm">
            {{
              $t(
                'Finish setting up two-factor authentication by scanning the following QR code using your authenticator application.'
              )
            }}
          </p>
          <div class="mt-4" data-cy="2fa-qr-code" v-html="twoFactorQrCode" />
        </article>

        <article>
          <h3 class="text-sm font-medium text-zinc-900 dark:text-white">
            {{ $t('Recovery codes') }}
          </h3>
          <p class="mt-1 text-sm">
            {{
              $t('Store these recovery codes in a secure place. They can be used to recover access to your account.')
            }}
          </p>
          <ul
            class="mt-4 select-all rounded border border-zinc-900/20 bg-zinc-50 p-3 font-mono text-xs dark:border-white/20 dark:bg-zinc-900"
            data-cy="2fa-recovery-codes"
          >
            <li v-for="code in twoFactorRecoveryCodes" :key="code" v-text="code" />
          </ul>
        </article>

        <article>
          <h3 class="text-sm font-medium text-zinc-900 dark:text-white">
            {{ $t('Confirm code') }}
          </h3>
          <p class="mt-1 text-sm">
            {{
              $t(
                'Enter the code generated by your authenticator application to verify that two-factor authentication is configured correctly.'
              )
            }}
          </p>
          <form class="mt-4 space-y-4" @submit.prevent="confirmCode">
            <BaseInput
              v-model="form.code"
              :error="form.errors.code"
              :label="$t('Two-factor code')"
              autocomplete="one-time-code"
              inverse
              required
              @input="form.clearErrors('code')"
            />

            <BaseButton :loading="form.processing" data-cy="submit-button" type="submit">
              {{ $t('Confirm code') }}
            </BaseButton>
          </form>
        </article>
      </template>
    </div>
  </TwoColumnBlockItem>
</template>

<script lang="ts" setup>
import TwoColumnBlockItem from '@/components/TwoColumnBlockItem.vue'
import { router, useForm } from '@inertiajs/vue3'
import { LockClosedIcon, LockOpenIcon } from '@heroicons/vue/24/outline'
import BaseBadge from '@/components/BaseBadge.vue'
import BaseInput from '@/components/BaseInput.vue'
import { computed, ref } from 'vue'
import { User } from '@/types/models'
import BaseButton from '@/components/BaseButton.vue'

type Props = {
  user: User
  status?: string
  twoFactorQrCode?: string
  twoFactorRecoveryCodes?: string[]
}

const props = defineProps<Props>()

const loading = ref<boolean>(false)

type TwoFactorForm = {
  code: string
}

const form = useForm<TwoFactorForm>({
  code: '',
})

const forceShowSetup = ref<boolean>(false)

const showSetup = computed<boolean>(() => {
  return props.status === 'two-factor-authentication-enabled' || form.hasErrors || forceShowSetup.value
})

function enableTwoFactor(): void {
  router.visit(route('two-factor.enable'), {
    method: 'post',
    preserveScroll: true,
    only: ['status', 'twoFactorQrCode', 'twoFactorRecoveryCodes'],
    onStart: () => {
      loading.value = true
    },
    onFinish: () => {
      loading.value = false
    },
  })
}

function disableTwoFactor(): void {
  router.visit(route('two-factor.disable'), {
    method: 'delete',
    preserveScroll: true,
    only: ['user'],
    onStart: () => {
      loading.value = true
    },
    onFinish: () => {
      loading.value = false
    },
  })
}

function confirmCode(): void {
  form.post(route('two-factor.confirm'), {
    errorBag: 'confirmTwoFactorAuthentication',
    preserveScroll: true,
    only: ['user', 'status', 'errors'],
    onError: () => {
      forceShowSetup.value = true
    },
  })
}
</script>
