<?php

return [
    'settings_meta_title' => 'Account settings',
    'settings_title' => 'Account settings',

    'profile_info_settings_title' => 'Profile information',
    'profile_info_settings_description' => 'Update your account\'s profile information and email address.',
    'profile_info_settings_button' => 'Update information',
    'profile_info_update_success' => [
        'title' => 'Profile updated',
        'message' => 'Your profile has been updated successfully.',
    ],

    'password_settings_title' => 'Password',
    'password_settings_description' => 'Update your account\'s password.',
    'password_settings_button' => 'Update password',

    '2fa_settings_title' => 'Two-factor authentication',
    '2fa_settings_description' => 'Add an extra layer of security to your account using two-factor authentication.',
    '2fa_settings_button_enable' => 'Enable 2FA',
    '2fa_settings_button_disable' => 'Disable 2FA',
    '2fa_settings_qr_code' => 'Finish setup',
    '2fa_settings_qr_code_description' => 'Finish setting up two-factor authentication by scanning the following QR code using your authenticator application.',
    '2fa_settings_recovery_codes' => 'Recovery codes',
    '2fa_settings_recovery_codes_description' => 'Store these recovery codes in a secure place. They can be used to recover access to your account.',
    '2fa_settings_confirm_code' => 'Confirm code',
    '2fa_settings_confirm_code_description' => 'Enter the code generated by your authenticator application to verify that two-factor authentication is configured correctly.',
    '2fa_settings_button_confirm' => 'Confirm code',
];
