<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used during authentication for various
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    'failed' => 'These credentials do not match our records.',
    'password' => 'The provided password is incorrect.',
    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',

    'register_meta_title' => 'Register',
    'register_title' => 'Create your account',
    'register_button' => 'Create account',
    'register_login_link' => 'Already have an account? Login here',
    'register_disabled' => 'Registration is currently disabled',

    'login_meta_title' => 'Login',
    'login_title' => 'Log in to Blast',
    'login_button' => 'Log in',
    'login_register_link' => 'Don\'t have an account? Register here',
    'login_forgot_password_link' => 'Forgot your password?',
    'login_remember' => 'Remember me',

    '2fa_challenge_meta_title' => 'Enter your two-factor code',
    '2fa_challenge_title' => 'Enter your two-factor code',
    '2fa_challenge_text' => 'Please enter the two-factor code generated by your authenticator application.',
    '2fa_challenge_button' => 'Confirm code',
    '2fa_challenge_recovery_link' => 'Use recovery code',

    '2fa_challenge_meta_recovery_title' => 'Enter your recovery code',
    '2fa_challenge_recovery_title' => 'Enter your recovery code',
    '2fa_challenge_recovery_text' => 'Please enter one of your recovery codes.',
    '2fa_challenge_recovery_button' => 'Confirm code',
    '2fa_challenge_link' => 'Use two-factor code',

    'forgot_password_meta_title' => 'Reset your password',
    'forgot_password_title' => 'Reset your password',
    'forgot_password_button' => 'Reset password',
    'forgot_password_success' => 'We sent a password reset link to :email. Please allow a few minutes for it to arrive.',

    'reset_password_meta_title' => 'Set new password',
    'reset_password_title' => 'Set new password',
    'reset_password_button' => 'Update password',

    'confirm_password_meta_title' => 'Confirm your password',
    'confirm_password_title' => 'Confirm your password',
    'confirm_password_text' => 'Please confirm your password before continuing.',
    'confirm_password_button' => 'Confirm password',

    'settings_meta_title' => 'Account settings',
    'settings_title' => 'Account settings',

    'profile_info_settings_title' => 'Profile information',
    'profile_info_settings_description' => 'Update your account\'s profile information and email address.',
    'profile_info_settings_button' => 'Update information',

    'password_settings_title' => 'Password',
    'password_settings_description' => 'Update your account\'s password.',
    'password_settings_button' => 'Update password',

    '2fa_settings_title' => 'Two-factor authentication',
    '2fa_settings_description' => 'Add an extra layer of security to your account using two-factor authentication.',
    '2fa_settings_button_enable' => 'Enable 2FA',
    '2fa_settings_button_disable' => 'Disable 2FA',
    '2fa_settings_qr_code' => 'Finish setup',
    '2fa_settings_qr_code_description' => 'Finish setting up two-factor authentication by scanning the following QR code using your authenticator application.',
    '2fa_settings_recovery_codes' => 'Recovery codes',
    '2fa_settings_recovery_codes_description' => 'Store these recovery codes in a secure place. They can be used to recover access to your account.',
    '2fa_settings_confirm_code' => 'Confirm code',
    '2fa_settings_confirm_code_description' => 'Enter the code generated by your authenticator application to verify that two-factor authentication is configured correctly.',
    '2fa_settings_button_confirm' => 'Confirm code',
];
