<template>
  <AppHead :title="recoveryMode ? $t('Enter your recovery code') : $t('Enter your two-factor code')" />

  <FullPageHeading :title="recoveryMode ? $t('Enter your recovery code') : $t('Enter your two-factor code')">
    <p>
      {{
        recoveryMode
          ? $t('Please enter one of your recovery codes.')
          : $t('Please enter the two-factor code generated by your authenticator application.')
      }}
    </p>
  </FullPageHeading>

  <div class="mt-10 space-y-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form v-if="recoveryMode" class="space-y-6" data-cy="2fa-recovery-form" @submit.prevent="submit">
      <TextInput
        v-model="recoveryForm.recovery_code"
        :error="recoveryForm.errors.code || recoveryForm.errors.recovery_code"
        :label="$t('Recovery code')"
        required
        @input="recoveryForm.clearErrors('recovery_code')"
      />

      <ButtonPrimary :loading="recoveryForm.processing" class="w-full" data-cy="submit-button" type="submit">
        {{ $t('Confirm code') }}
      </ButtonPrimary>
    </form>

    <form v-else class="space-y-6" data-cy="2fa-challenge-form" @submit.prevent="submit">
      <TextInput
        v-model="challengeForm.code"
        :error="challengeForm.errors.code"
        :label="$t('Two-factor code')"
        autocomplete="one-time-code"
        required
        @input="challengeForm.clearErrors('code')"
      />

      <ButtonPrimary :loading="challengeForm.processing" class="w-full" data-cy="submit-button" type="submit">
        {{ $t('Confirm code') }}
      </ButtonPrimary>
    </form>

    <div>
      <ButtonSecondary as="button" class="w-full" data-cy="switch-mode-button" @click="switchMode">
        {{ recoveryMode ? $t('Use two-factor code') : $t('Use recovery code') }}
      </ButtonSecondary>
    </div>
  </div>
</template>

<script lang="ts" setup>
import FullPageLayout from '@/layouts/FullPageLayout.vue'
import FullPageHeading from '@/components/FullPageHeading.vue'
import AppHead from '@/components/AppHead.vue'
import TextInput from '@/components/AppInput.vue'
import { useForm } from '@inertiajs/vue3'
import ButtonPrimary from '@/components/ButtonPrimary.vue'
import ButtonSecondary from '@/components/ButtonSecondary.vue'
import { ref } from 'vue'

defineOptions({
  layout: FullPageLayout,
})

const recoveryMode = ref<boolean>(false)

type TwoFactorChallengeForm = {
  code: string
}

const challengeForm = useForm<TwoFactorChallengeForm>({
  code: '',
})

type TwoFactorRecoveryForm = {
  recovery_code: string
  code?: string
}

const recoveryForm = useForm<TwoFactorRecoveryForm>({
  recovery_code: '',
})

function submit(): void {
  if (recoveryMode.value) {
    recoveryForm.post(route('two-factor.login'))
  } else {
    challengeForm.post(route('two-factor.login'))
  }
}

function switchMode(): void {
  recoveryMode.value = !recoveryMode.value
}
</script>
