name: Browser Tests

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ created ]

concurrency:
  group: browser-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: testing
          MYSQL_USER: blast
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: redis, xdebug, mysql
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare environment
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Compile assets
        run: npm install && npm run build

      - name: Run migrations
        run: php artisan migrate --force --no-interaction

      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          start: php artisan serve --port=8000
          install: false
          config: baseUrl=http://localhost:8000
          wait-on: 'http://localhost:8000'