name: Release

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy production
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.ENVOYER_DEPLOYMENT_HOOK }}
          method: 'POST'
          contentType: 'application/x-www-form-urlencoded'
          data: '{"sha": "${{ github.event.release.target_commitish }}"}'
