name: Tests

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
                    coverage: none

            -   name: Install dependencies
                run: composer install --no-interaction --no-progress --no-suggest

            -   name: Run tests
                run: vendor/bin/phpunit